Laravel Mix compilacion y enqueues preparo terreno

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,65 +1,70 @@
-sudo: false
-dist: trusty
+# Travis CI configuration file.
+# @link https://travis-ci.org/
 
+# For use with the Alecaddd WordPress Starter Theme
+# @link https://github.com/Alecaddd/awps
+
+# Ditch sudo and use containers.
+# @link http://docs.travis-ci.com/user/migrating-from-legacy/#Why-migrate-to-container-based-infrastructure%3F
+# @link http://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure
+sudo: false
+
+# Declare project language.
+# @link http://about.travis-ci.org/docs/user/languages/php/
 language: php
 
-notifications:
-  email:
-    on_success: never
-    on_failure: change
-
-branches:
-  only:
-    - master
-
+# Cache composer for faster build
 cache:
   directories:
-    - $HOME/.composer/cache
+    # Cache directory for older Composer versions.
+    - $HOME/.composer/cache/files
+    # Cache directory for more recent Composer versions.
+    - $HOME/.cache/composer/files
 
+# Declare versions of PHP to use. Use one decimal max.
+# @link http://docs.travis-ci.com/user/build-configuration/
 matrix:
-  include:
-    - php: 7.2
-      env: WP_VERSION=latest
-    - php: 7.1
-      env: WP_VERSION=latest
-    - php: 7.0
-      env: WP_VERSION=latest
-    - php: 5.6
-      env: WP_VERSION=latest
-    - php: 5.6
-      env: WP_VERSION=trunk
-    - php: 5.6
-      env: WP_TRAVISCI=phpcs
-    - php: 5.3
-      env: WP_VERSION=latest
-      dist: precise
+    fast_finish: true
+
+    include:
+        # Current $required_php_version for WordPress: 5.2.4
+        # This theme uses namespaces and autoload
+        # and can't run on version < 5.6
+        - php: "7.2"
+        - php: "7.3"
+        - php: "7.4"
+        - php: "nightly"
+          # Use this to prepare your build for testing.
+          # e.g. copy database configurations, environment variables, etc.
+          # Failures in this section will result in build status 'errored'.
+          before_install:
+            # disable Xdebug to speed up building process
+            - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
+            # Install PHP packages.
+            - composer install --ansi --prefer-dist --no-suggest
+            # Install ESLint shareable config for WordPress.
+            # @link https://github.com/WordPress-Coding-Standards/eslint-config-wordpress
+            - npm install eslint eslint-config-wordpress
+          # Run test script commands.
+          # Default is specific to project language.
+          # All commands must exit with code 0 on success. Anything else is considered failure.
+          script:
+            # Run the theme through ESLint.
+            - npm run lint
+            # WordPress Coding Standards and PHPCompatibility.
+            # @link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
+            # @link http://pear.php.net/package/PHP_CodeSniffer/
+            # @link https://github.com/PHPCompatibility/PHPCompatibilityWP
+            - composer test
 
 before_script:
-  - export PATH="$HOME/.composer/vendor/bin:$PATH"
-  - |
-    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
-      phpenv config-rm xdebug.ini
-    else
-      echo "xdebug.ini does not exist"
-    fi
-  - |
-    if [[ ! -z "$WP_VERSION" ]] ; then
-      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
-      composer global require "phpunit/phpunit=4.8.*|5.7.*"
-    fi
-  - |
-    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
-      composer global require wp-coding-standards/wpcs
-      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
-    fi
-
+  # Install PHP packages.
+  - composer install --ansi --prefer-dist --no-suggest
 script:
-  - |
-    if [[ ! -z "$WP_VERSION" ]] ; then
-      phpunit
-      WP_MULTISITE=1 phpunit
-    fi
-  - |
-    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
-      phpcs
-    fi
+  # Search for PHP syntax errors.
+  - composer test
+
+# Receive notifications for build results.
+# @link http://docs.travis-ci.com/user/notifications/#Email-notifications
+notifications:
+    email: false
